initLicense: Apache-2.0

initScope: larry1123

compressionLevel: 0

packageExtensions:
  eslint-module-utils@*:
    peerDependencies:
      eslint-import-resolver-node: "*"
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      typescript: "*"
  ts-node@*:
    peerDependencies:
      ttypescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpMode: strict

yarnPath: scripts/run-yarn.js
